// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlqKz5QktguYAzN42oQYJe19e7dUJgls',
    appId: '1:128967553160:web:d738c164cba310706eaf3d',
    messagingSenderId: '128967553160',
    projectId: 'appchat-7505e',
    authDomain: 'appchat-7505e.firebaseapp.com',
    storageBucket: 'appchat-7505e.firebasestorage.app',
    measurementId: 'G-GZ3PCX5LRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUL-5dF-JXVZwSS_VCQeJgLmYyACxiaB0',
    appId: '1:128967553160:android:5e8ebcb8ce76a55d6eaf3d',
    messagingSenderId: '128967553160',
    projectId: 'appchat-7505e',
    storageBucket: 'appchat-7505e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlqKz5QktguYAzN42oQYJe19e7dUJgls',
    appId: '1:128967553160:web:f8bef4ecfda230236eaf3d',
    messagingSenderId: '128967553160',
    projectId: 'appchat-7505e',
    authDomain: 'appchat-7505e.firebaseapp.com',
    storageBucket: 'appchat-7505e.firebasestorage.app',
    measurementId: 'G-F40ENE9R4X',
  );
}
